spring:
  application:
    name: live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:db-sharding.yaml
    hikari:
      pool-name: user-pool
      maximum-pool-size: 300
      minimum-idle: 15
      idle-timeout: 60000
      connection-timeout: 4000
      max-lifetime: 60000

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://106.15.104.19:8848?namespace=test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9090
