#spring:
#  application:
#    name: live-user-provider
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:db-sharding.yaml
#    hikari:
#      pool-name: user-pool
#      maximum-pool-size: 300
#      minimum-idle: 15
#      idle-timeout: 60000
#      connection-timeout: 4000
#      max-lifetime: 60000
#
#  data:
#    redis:
#      port: 6379
#      #      host: 127.0.0.1
#      host: 106.15.104.19
#      lettuce:
#        pool:
#          min-idle: 10
#          max-idle: 20
#          max-active: 50
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://106.15.104.19:8848?namespace=test&&username=nacos&&password=nacos
#  protocol:
#    name: dubbo
#    port: 9090
#
#live:
#  rmq:
#    producer:
#      name-srv: 106.14.246.27:9876
#      group-name: ${spring.application.name}
#      retry-times: 3
#      send-time-out: 3000
#    consumer:
#      group-name: ${spring.application.name}
#      name-srv: 106.14.246.27:9876